name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r AI/requirements.txt

      - name: Lint import
        run: |
          python - <<'PY'
          import importlib
          for m in [
            'fastapi','uvicorn','pandas','numpy','torch','ta','transformers','backtrader','streamlit','websocket','dotenv'
          ]:
              try:
                  importlib.import_module(m)
                  print('ok', m)
              except Exception as e:
                  raise SystemExit(f'Failed import: {m}: {e}')
          PY

      - name: Build Docker
        run: |
          docker build -t crypto-ai:ci ./AI
